### ISSUE TITLE
Update `generate_projection_codes.jl`

### ISSUE THREAD

**Issue by visr** [JuliaGeo/Proj.jl#24]
With #23 we switched to PROJ 6.1.0. The files that the `generate_projection_codes.jl` script relied on are no longer included as is, but the information is in a SQLite database named `proj.db`. That means we currently cannot easily update the projection codes.

We should either update `generate_projection_codes.jl` to work with `proj.db`, or perhaps even refactor such that we don't rely on these generated codes at all.

**Comment by c42f** [comment]
My feeling about the code list and associated transformation definitions was that they are handy for low precision use but of questionable reliability for "real work".

In some ways they just constitute a footgun for unwary novice users, there being no obvious quality control in terms of accuracy, provenance (or sometimes even invertability! At least with older versions of proj.4).

Well, this was the situation last I dealt with these codes so in some ways it might better just to delete them. What I did find the list really useful for was mainly the comments and as a starting point for further investigation.

**Comment by visr** [comment]
Great, it's valuable to get your input even though you are not using it directly anymore.

**Comment by visr** [comment]
Closing this, as I don't think it's needed anymore since `Proj.Transformation` accepts both EPSG codes and proj strings.
