### ISSUE TITLE
geodesic functions are broken

### ISSUE THREAD

**Issue by adigitoleo** [JuliaGeo/Proj.jl#56]
I was just having a look for some geodesic functions in Julia, and I've noticed that various (all?) `geod_*` functions in here don't work as expected, on a few levels:

- no documentation in the Juia shell, e.g. `?geod_inverse` just spits out the line number (even with `has_geodesic_support`).
- ~~missing return statements (easy fix)~~
- ccall to (at least) `:geod_inverse` is not working (I'm getting NaNs everywhere)
- the `_geod_inverse` wrapped in `geod_inverse` thing seems unnecessary because of dispatch on `Vector{Cdouble}`
- the API is clunky compared to [GeographicLib.jl](https://github.com/anowacki/GeographicLib.jl)

Opening this for visibility, I'll try to work on cleaning some of these up if I can.

**Comment by adigitoleo** [comment]
Ah OK after a bit more investigation I've found the other discussions here about potential larger changes to the package, so I'll just use GeograhicLib for now. Happy to help as I learn more about Julia and proj.

**Comment by visr** [comment]
Currently only the ccalls remain, though they should be usable. I've opened #66 to discuss possibly building a new API on top.
