### ISSUE TITLE
failed to precompile on macOS 10.15.7

### ISSUE THREAD

**Issue by melodyjulia** [JuliaGeo/Proj.jl#68]
It prompts the following error:
Failed to precompile Proj [c94c279d-25a6-4763-9509-64d165bea63e] to /Users/test/.julia/compiled/v1.7/Proj/jl_PId02S.
ERROR: LoadError: InitError: could not load library "/Users/test/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.dylib"
dlopen(/Users/test/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.dylib, 1): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /Users/test/.julia/artifacts/525a7050baaa2b0732225f4528525dfb3cfed1df/lib/libproj.25.9.0.1.dylib
  Reason: Incompatible library version: libproj.25.dylib requires version 13.0.0 or later, but libcurl.4.dylib provides version 12.0.0

**Comment by visr** [comment]
Thanks for the report. I noticed the same. This is now fixed after https://github.com/JuliaPackaging/Yggdrasil/pull/5301.

The new binaries from https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/tag/PROJ-v900.0.100%2B1 should automatically be picked up if you update `PROJ_jll`.
