### ISSUE TITLE
PROJ_jll v900.100 breaks (online?) transformation

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/Proj.jl#71]
In v1.0 with the old PROJ_jll this worked fine:

```julia
julia> Proj.enable_network!()
julia> trans = Proj.Transformation("EPSG:4326", "EPSG:4326+3855")  # ellipsoid to egm2008 height
julia> trans(0,0,0)
(0.0, 0.0, -17.0154953)
```

In the new _jll I get `(0,0,0)`, without any errors. Looking at the projinfo output, it seems it skips all pipelines requiring (online) vertical grid transform data and arrives at the last noop operation.

**Comment by evetion** [comment]
This one does work:
```julia
trans = Proj.Transformation("EPSG:4979", "EPSG:3855")
```

**Comment by evetion** [comment]
I think this is at the source of the issue: https://github.com/OSGeo/PROJ/pull/3119

**Comment by visr** [comment]
Ah yes, that looks like the same reason I needed to update some of the tests in #70.

**Comment by visr** [comment]
I think this can be closed, right? PROJ behavior changed, not much to do here.

**Comment by evetion** [comment]
We could place a warning in the README to pin PROJ versions? As the API might not break, but your results might suddenly change? I dislike this behaviour.

**Comment by visr** [comment]
Yeah it might be a good idea to mention that if transformations need to stay exactly the same, users should fix the PROJ_jll version.
