### ISSUE TITLE
support for GeoFormatTypes.jl

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaGeo/Proj.jl#85]
Should Proj.Transformation accept GeoFormatTypes?

e.g. `Proj.Transformation(EPSG(4326), EPSG(3413))`

From the docs it seems that this should be supported. I'm happy to generate a PR.

**Comment by rafaqz** [comment]
I think support might just be incomplete?

You can just do `convert(String, crs)` for most and proj will read it. 

PR would be great
