### ISSUE TITLE
Would be good to add a to_epsg implimentation 

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaGeo/Proj.jl#88]
robustly retrieving the epsg from a crs requires an implementation of pyproj's [to_epsg](https://github.com/pyproj4/pyproj/blob/1452ba404be58c14a6b64d4551c320022f5aafcf/pyproj/_crs.pyx#L2746C1-L2747C5)

**Comment by visr** [comment]
Isn't this already present?

https://github.com/JuliaGeo/Proj.jl/blob/d88918ca72426245bcf52889854ad2aa08d1e7c8/src/crs.jl#L129-L133

Although it looks like this doesn't use `proj_get_id_auth_name` to check if it is EPSG, so that's a bug.

**Comment by alex-s-gardner** [comment]
I believe this is a very limited version of [to_epsg](https://github.com/pyproj4/pyproj/blob/1452ba404be58c14a6b64d4551c320022f5aafcf/pyproj/_crs.pyx#L2746C1-L2747C5) as it can only find an EPSG code if the Authority and code is contained in the CRS. For example it can't infer the EPSG code from a ProjString or wkt that does not include the authority. This is the same limitation as my [ArchGDAL]( PRhttps://github.com/yeesian/ArchGDAL.jl/pull/391). `to_epsg` has a bunch of logic to try and infer the EPSG and also returns a confidence level that it found the right code.

**Comment by alex-s-gardner** [comment]
I think we'll need to use [Proj.proj_identify](https://github.com/JuliaGeo/Proj.jl/blob/0e32ea7901ca5a1664d3a607dd21f8972d558367/src/libproj.jl#L1350)

**Comment by alex-s-gardner** [comment]
Can someone provide an example of how to use [Proj.proj_identify](https://github.com/JuliaGeo/Proj.jl/blob/0e32ea7901ca5a1664d3a607dd21f8972d558367/src/libproj.jl#L1350), I can't seem to figure out how to assign and retrieve the C objects.

**Comment by alex-s-gardner** [comment]
Should we introduce this into proj as `to_epsg()` then use that for [`GFT.EPSG(crs::CRS)`](https://github.com/JuliaGeo/Proj.jl/blob/d88918ca72426245bcf52889854ad2aa08d1e7c8/src/crs.jl#L129-L133)?

**Comment by visr** [comment]
Yeah perhaps we can create a `Proj.identify` that is a nicely wrapped version of the C API `Proj.proj_identify`.

Then for `GFT.EPSG(crs::CRS)` we can use that function with auth set to CRS and only accepting a confidence of 70 or higher like pyproj.

I just noticed my use of `out_confidence` was incorrect, that is an array that is filled by proj with the confidence level per entry.

**Comment by alex-s-gardner** [comment]
In the example above how should `out_confidence` be initialized then? I don't have a great mental model yet when 
calling out to `C`

**Comment by visr** [comment]
Hmm yeah I'm also not great with this stuff, but managed to figure it out, see the updated example.

So you need a reference to a pointer of the right type. We can initialize this with a null pointer, PROJ will point it to an array that it allocates itself. After calling the function we can see that `out_confidence[]` now points somewhere, and use `unsafe_load` to get the value. In this example I got 70. Note the C API docs that explain that we have to free the PROJ allocated array ourselves with `Proj.proj_int_list_destroy(out_confidence[])`.

**Comment by alex-s-gardner** [comment]
I'll work on a PR

**Comment by alex-s-gardner** [comment]
@visr for the higher level `identify` we should just return the top result. I can really see a use case for returning all matches. If that functionality is needed the user can drop a level to `proj_identify`

**Comment by alex-s-gardner** [comment]
@visr I think this is good to merge. If you agree I will work on to_EPSG next

**Comment by visr** [comment]
Left some comments on #92. For `to_EPSG` you mean `GFT.EPSG(crs::CRS)` right?
